apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  selector:
    matchLabels:
      io.kompose.service: app
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: app
    spec:
      containers:
      - name: app
        image: naing2victor/app:2.0
        # ports:
        # - containerPort: 9000
        # protocol: TCP
        volumeMounts:
        - name: pvc
          mountPath: /var/www/
        - name: pvc
          mountPath: /usr/local/etc/php/conf.d/local.ini
        env:
        - name: DB_CONNECTION
          valueFrom:
            configMapKeyRef:
              key: DB_CONNECTION
              name: database-env
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              key: DB_HOST
              name: database-env
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              key: DB_DATABASE
              name: database-env
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              key: DB_PORT
              name: database-env
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              key: DB_USERNAME
              name: database-secret
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              key: DB_PASSWORD
              name: database-secret
        - name: SERVICE_NAME
          value: app
        - name: SERVICE_TAG
          value: dev
        workingDir: /var/www/
        resources: {}
        tty: true
      restartPolicy: Always
      volumes:
      - name: pvc
        persistentVolumeClaim:
          claimName: pvc
status: {}
