apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: app
  name: app
spec:
  selector:
    matchLabels:
      io.kompose.service: app
  replicas: 1
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: app
    spec:
      containers:
      - env:
        - name: APP_KEY
          value: base64:xBSpqMa3n6pzvryc+lyYO0zYhFsYFp7GXQZ3L3ewloI=
        - name: APP_NAME
          value: Laravel
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              key: DB_DATABASE
              name: app-env
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              key: DB_PORT
              name: app-env
        - name: SERVICE_NAME
          value: app
        - name: SERVICE_TAGS
          value: dev
        image: naing2victor/php:7.2
        name: app
        ports:
        - containerPort: 8080
        resources: {}
        tty: true
        workingDir: /var/www
      restartPolicy: Always
status: {}
