apiVersion: v1
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: app-env
  name: app-env
data:
  APP_NAME: Laravel
  APP_ENV: local
  APP_KEY: base64:T3qW4VqzbLVtmIckD8DkMZE9kqs+SUDI9z0MQ94vKV0=
