apiVersion: v1
data:
  APP_DEBUG: "true"
  APP_ENV: local
  APP_KEY: T3qW4VqzbLVtmIckD8DkMZE9kqs+SUDI9z0MQ94vKV0=
  APP_NAME: Laravel
  DB_CONNECTION: mysql
  DB_DATABASE: bGFyYXZlbA==
  DB_HOST: 127.0.0.1
  DB_PASSWORD: laraveluser
  DB_PORT: "3306"
  DB_USERNAME: laraveluser
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: app-env
  name: app-env
