apiVersion: v1
data:
  APP_DEBUG: "true"
  APP_ENV: local
  APP_KEY: base64:T3qW4VqzbLVtmIckD8DkMZE9kqs+SUDI9z0MQ94vKV0=
  APP_NAME: Laravel
  APP_URL: http://localhost
  AWS_ACCESS_KEY_ID: ""
  AWS_BUCKET: ""
  AWS_DEFAULT_REGION: us-east-1
  AWS_SECRET_ACCESS_KEY: ""
  BROADCAST_DRIVER: log
  CACHE_DRIVER: file
  DB_CONNECTION: mysql
  DB_DATABASE: laravel
  DB_HOST: 127.0.0.1
  DB_PASSWORD: laraveluser
  DB_PORT: "3306"
  DB_USERNAME: laraveluser
  LOG_CHANNEL: stack
  MAIL_DRIVER: smtp
  MAIL_ENCRYPTION: "null"
  MAIL_FROM_ADDRESS: "null"
  MAIL_FROM_NAME: Laravel
  MAIL_HOST: smtp.mailtrap.io
  MAIL_PASSWORD: "null"
  MAIL_PORT: "2525"
  MAIL_USERNAME: "null"
  MIX_PUSHER_APP_CLUSTER: mt1
  MIX_PUSHER_APP_KEY: ""
  PUSHER_APP_CLUSTER: mt1
  PUSHER_APP_ID: ""
  PUSHER_APP_KEY: ""
  PUSHER_APP_SECRET: ""
  QUEUE_CONNECTION: sync
  REDIS_HOST: 127.0.0.1
  REDIS_PASSWORD: "null"
  REDIS_PORT: "6379"
  SESSION_DRIVER: file
  SESSION_LIFETIME: "120"
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: app-env
  name: app-env
