apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: database
  name: database
spec: 
  selector:
    matchLabels:
      io.kompose.service: database
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: database
    spec:
      containers:
      - env:
        - name: DB_DATABASE
          valueFrom:
            configMapKeyRef:
              key: DB_DATABASE
              name: database-env
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              key: DB_PORT
              name: database-env
        - name: DB_USERNAME
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: DB_USERNAME
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: DB_PASSWORD
        - name: DB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: DB_ROOT_PASSWORD
        - name: SERVICE_NAME
          value: database
        - name: SERVICE_TAG
          value: dev
        image: mysql:5.7
        name: database
        ports:
        - containerPort: 3306
          name: database
        resources: {}
        tty: true
        volumeMounts:
        - mountPath: /var/lib/mysql/
          name: database-claim0-persistentvolumeclaim
      restartPolicy: Always
      volumes:
      - name: database-claim0-persistentvolumeclaim
        persistentVolumeClaim:
          claimName: database-claim0
status: {}
