apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: database
  name: database
spec: 
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: database
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: laravel
        - name: MYSQL_PASSWORD
          value: laravel
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_USERNAME
          value: laravel
        - name: SERVICE_NAME
          value: mysql
        - name: SERVICE_TAGS
          value: dev
        image: mysql:5.7
        name: database
        ports:
        - containerPort: 3306
          name: database
        resources: {}
        tty: true
        volumeMounts:
        - mountPath: /var/lib/mysql/
          name: dbdata
        - mountPath: /etc/mysql/my.cnf
          name: database-claim1
      restartPolicy: Always
      volumes:
      - name: dbdata
        persistentVolumeClaim:
          claimName: dbdata
      - name: database-claim1
        persistentVolumeClaim:
          claimName: database-claim1
status: {}
