apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: database
  name: database
spec: 
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: database
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: database
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: database-env
        - secretRef:
            name: database-secret
        image: mysql:5.7
        name: database
        ports:
        - containerPort: 3306
          name: database
        resources: {}
        tty: true
        volumeMounts:
        - mountPath: /var/lib/mysql/
          name: pvc
      restartPolicy: Always
      volumes:
      - name: pvc
        persistentVolumeClaim:
          claimName: pvc
status: {}
