apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/1/./kompose-linux-amd64 convert -f docker-compose.yml
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: database
  name: database
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: database
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
          value: laravel
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: SERVICE_NAME
          value: mysql
        - name: SERVICE_TAGS
          value: dev
        image: mysql:5.7
        name: database
        ports:
        - containerPort: 3306
        resources: {}
        tty: true
      restartPolicy: Always
status: {}
