version: '3'
services:

  #PHP Service
  app:
    container_name: app
    image: naing2victor/php:7.2
    restart: always
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    working_dir: /var/www

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: always
    tty: true
    ports:
      - "80:80"
      - "443:443"

  #MySQL Service
  database:
    image: mysql:5.7
    container_name: database
    restart: always
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "laravel"
      MYSQL_ROOT_PASSWORD: "root"
      SERVICE_TAGS: "dev"
      SERVICE_NAME: "mysql"
