version: '3'
services:

  #PHP Service
  app:
    container_name: app
    image: naing2victor/php:7.2
    restart: always
    env_file: .env
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
      APP_NAME: Laravel
      APP_KEY: base64:xBSpqMa3n6pzvryc+lyYO0zYhFsYFp7GXQZ3L3ewloI=
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
 
  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: always
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
 
  #MySQL Service
  database:
    image: mysql:5.7
    container_name: database
    restart: always
    tty: true
    environment:
      SERVICE_TAGS: "dev"
      SERVICE_NAME: "mysql"
      MYSQL_DATABASE: "laravel"
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USERNAME: "laravel"
      MYSQL_PASSWORD: "laravel"
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql/
      - ./mysql/my.cnf:/etc/mysql/my.cnf

#Volumes
volumes:
  dbdata:
    driver: local
