apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: pv
  name: pv
spec:
  storageClassName: vol
  capacity:
	storage: 5Gi
  accessModes:
	- ReadWriteOnce
  hostPath:
	path: "/home/naing/project"
