apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: /snap/kompose/1/./kompose-linux-amd64 convert -f docker-compose.yml
    kompose.version: 1.18.0 (06a2e56)
  creationTimestamp: null
  labels:
    io.kompose.service: webserver
  name: webserver
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: webserver
    spec:
      containers:
      - image: nginx:alpine
        name: webserver
        ports:
        - containerPort: 80
        - containerPort: 443
        resources: {}
        tty: true
      restartPolicy: Always
status: {}
