apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.19.0 (f63a961c)
  creationTimestamp: null
  labels:
    io.kompose.service: webserver
  name: webserver
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: webserver
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.19.0 (f63a961c)
      creationTimestamp: null
      labels:
        io.kompose.service: webserver
    spec:
      containers:
      - image: nginx:alpine
        name: webserver
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /var/www/
          name: pvc
        - mountPath: /etc/nginx/conf.d/
          name: webserver-env
        resources: {}
        tty: true
      restartPolicy: Always
      volumes:
      - name: pvc
        persistentVolumeClaim:
          claimName: pvc
      - name: webserver-env
        configMap:
          name: webserver-env
status: {}
